name: Run Tests!

on: [push, pull_request]

jobs:
  tests:
    name: run pytest inside sb3 docker container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build container # use docker buildx for caching?
        run: bash docker/bin/build_container.sh

      - name: Run Tests
        run: bash docker/bin/test.sh